# MkDocs Material 配置（docs-site）
site_name: Minecraft @minecraft 类型文档
site_url: https://MCxlm1.github.io/minecraft-doc/
repo_url: https://github.com/MCxlm1/minecraft-doc
docs_dir: site
site_dir: _site
use_directory_urls: true

theme:
  name: material
  language: zh
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - stylesheets/custom.css
